[build]
  base = "frontend"
  command = "yarn install && yarn build" 
  publish = ".next"

# This plugin is essential for Next.js with App Router and Server Components
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Optional: Set environment variables for different contexts
[context.production.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"