[build]
  base = "frontend"
  command = "corepack enable && yarn install --immutable && yarn build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  NODE_ENV = "production"
  YARN_NPM_REGISTRY_SERVER = "https://registry.npmjs.org"
  npm_config_registry = "https://registry.npmjs.org"

[context.deploy-preview.environment]
  NODE_ENV = "production"
  YARN_NPM_REGISTRY_SERVER = "https://registry.npmjs.org"
  npm_config_registry = "https://registry.npmjs.org"
