[build]
  base = "frontend"
  command = "corepack enable && yarn install --immutable && yarn build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"
  YARN_NPM_REGISTRY_SERVER = "https://registry.npmjs.org"
  COREPACK_ENABLE_STRICT = "0"

[context.deploy-preview.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"
  YARN_NPM_REGISTRY_SERVER = "https://registry.npmjs.org"
  COREPACK_ENABLE_STRICT = "0"
